I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 276, in script
    y "..."
  File "game/script.rpy", line 62, in speaker_callback
    renpy.voice.play(renpy.random.choice(sound), fadein=0.001)
AttributeError: module 'renpy.exports' has no attribute 'voice'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 276, in script
    y "..."
  File "D:\Programas\RenPy\renpy-8.1.1-sdk\renpy\ast.py", line 930, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "D:\Programas\RenPy\renpy-8.1.1-sdk\renpy\exports.py", line 1473, in say
    who(what, *args, **kwargs)
  File "D:\Programas\RenPy\renpy-8.1.1-sdk\renpy\character.py", line 1352, in __call__
    self.do_display(who, what, cb_args=self.cb_args, dtt=dtt, **display_args)
  File "D:\Programas\RenPy\renpy-8.1.1-sdk\renpy\character.py", line 1003, in do_display
    display_say(who,
  File "D:\Programas\RenPy\renpy-8.1.1-sdk\renpy\character.py", line 601, in display_say
    c("show", interact=interact, type=type, **cb_args)
  File "game/script.rpy", line 62, in speaker_callback
    renpy.voice.play(renpy.random.choice(sound), fadein=0.001)
AttributeError: module 'renpy.exports' has no attribute 'voice'

Windows-10-10.0.22621 AMD64
Ren'Py 8.1.1.23060707
test01 1.0
Fri Aug 18 17:24:46 2023
