I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 27, in script
    define r = Character("RIBERTO", who_bold = false, what_prefix = '"', what_suffix = '"')
  File "game/script.rpy", line 27, in script
    define r = Character("RIBERTO", who_bold = false, what_prefix = '"', what_suffix = '"')
  File "game/script.rpy", line 27, in <module>
    define r = Character("RIBERTO", who_bold = false, what_prefix = '"', what_suffix = '"')
NameError: name 'false' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "C:\Users\Cynthia\Descargas\programas\RENPY\renpy-8.0.3-sdk\renpy\bootstrap.py", line 277, in bootstrap
    renpy.main.main()
  File "C:\Users\Cynthia\Descargas\programas\RENPY\renpy-8.0.3-sdk\renpy\main.py", line 558, in main
    renpy.game.context().run(node)
  File "game/script.rpy", line 27, in script
    define r = Character("RIBERTO", who_bold = false, what_prefix = '"', what_suffix = '"')
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python3.9/site-packages/future/utils/__init__.py", line 441, in raise_
  File "game/script.rpy", line 27, in script
    define r = Character("RIBERTO", who_bold = false, what_prefix = '"', what_suffix = '"')
  File "C:\Users\Cynthia\Descargas\programas\RENPY\renpy-8.0.3-sdk\renpy\ast.py", line 2441, in execute
    self.set()
  File "C:\Users\Cynthia\Descargas\programas\RENPY\renpy-8.0.3-sdk\renpy\ast.py", line 2455, in set
    value = renpy.python.py_eval_bytecode(self.code.bytecode)
  File "C:\Users\Cynthia\Descargas\programas\RENPY\renpy-8.0.3-sdk\renpy\python.py", line 1085, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 27, in <module>
    define r = Character("RIBERTO", who_bold = false, what_prefix = '"', what_suffix = '"')
NameError: name 'false' is not defined

Windows-10-10.0.19041 AMD64
Ren'Py 8.0.3.22090809
test01 1.0
Sat Jan  7 02:41:00 2023
